version: "3.1"

services:
  tier-idp:
    build: .

  test-sp:
    image: unicon/shibboleth-sp
    container_name: test-sp
    volumes:
      - ./test-sp/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
      - ./test-sp/sp.conf:/etc/httpd/conf.d/sp.conf


