version: "3.1"

services:
  tier-idp:
    build: .
    volumes:
      - metadata:/opt/shibboleth-idp/metadata/
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    container_name: tier-idp
    stop_signal: RTMIN+3
    environment:
      - container=docker
    tmpfs:
      - /run
      - /tmp
    cap_add:
      - SYS_ADMIN
    expose:
      - "8080"
      - "8443"
    networks:
      - example

  idp-kerberos:
    build: kerberos/
    container_name: idp-kdc
    networks:
      - example

  test-sp:
    image: unicon/shibboleth-sp
    container_name: test-sp
    volumes:
      - ./test-sp/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
      - metadata:/etc/shibboleth/metadata
      - ./index.html:/var/www/html/secure/index.html

volumes:
  metadata:

networks:
  example:
